version: '3.7'

services:
  db:
    image: mysql:8.0.19
    container_name: comusic_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
  
  api:
    build:
      context: .
      target: builder
    container_name: comusic_api
    volumes:
      - ./:/build
      # See environment.GOOGLE_APPLICATION_CREDENTIALS
      # - /path/to/host/credentials/directory:/credentials
    command: make dev
    ports:
      - 1323:1323
    environment:
      DEBUG: 'true'
      DSN: mysql://user:userpass@tcp(db:3306)/database?parseTime=true
      # Local directory to upload files.
      UPLOADS_DIR: /build/uploads
      # Base URL to retrieve the uploaded files.
      UPLOADS_PATH: http://localhost:1323/uploads
      # Config file for dev at: ./centrifugo/config.dev.json
      CENTRIFUGO_API_KEY: 5f8661e7-e7c4-4436-ad65-c3a5ac5e8a66
      CENTRIFUGO_SECRET: 64915974-efe3-495c-aa77-2a9b263991cf
      CENTRIFUGO_URL: http://centrifugo:8000

      # Set path to firebase adminsdk json file.
      # As an example, it's put in /credentials directory on container which is
      # connected to /path/to/host/credentials/directory, as configured at volumes directive above.
      # GOOGLE_APPLICATION_CREDENTIALS: /credentials/<firebase_adminsdk.json>

      #SENDGRID_API_KEY: <sendgrid-api-key>

    centrifugo:
    image: centrifugo/centrifugo
    container_name: comusic_centrifugo
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo -c config.dev.json
    ports:
      - 8888:8000